[env:anchor1]
platform        = espressif32
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework       = arduino
monitor_speed   = 115200
build_flags     =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NODE_ROLE_ANCHOR
    -D ANCHOR_ID=1
; CALIBRATION_MODE is NOT set here → defaults to 0 (normal)

[env:anchor1_cal]
platform        = espressif32
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework       = arduino
monitor_speed   = 115200
build_flags     =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NODE_ROLE_ANCHOR
    -D ANCHOR_ID=1
    -D CALIBRATION_MODE=1
    -D CORE_DEBUG_LEVEL=4

[env:anchor2]
platform        = espressif32
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework       = arduino
monitor_speed   = 115200
build_flags     =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NODE_ROLE_ANCHOR
    -D ANCHOR_ID=2

[env:anchor2_cal]
platform        = espressif32
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework       = arduino
monitor_speed   = 115200
build_flags     =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NODE_ROLE_ANCHOR
    -D ANCHOR_ID=2
    -D CALIBRATION_MODE=1

[env:anchor3]
platform        = espressif32
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework       = arduino
monitor_speed   = 115200
build_flags     =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NODE_ROLE_ANCHOR
    -D ANCHOR_ID=3

[env:anchor3_cal]
platform        = espressif32
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework       = arduino
monitor_speed   = 115200
build_flags     =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NODE_ROLE_ANCHOR
    -D ANCHOR_ID=3
    -D CALIBRATION_MODE=1

[env:anchor4]
platform        = espressif32
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework       = arduino
monitor_speed   = 115200
build_flags     =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NODE_ROLE_ANCHOR
    -D ANCHOR_ID=4

[env:anchor4_cal]
platform        = espressif32
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework       = arduino
monitor_speed   = 115200
build_flags     =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NODE_ROLE_ANCHOR
    -D ANCHOR_ID=4
    -D CALIBRATION_MODE=1